volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:18
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/18/docker
  backend:
    image: trueorfalse8/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: trueorfalse8/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: trueorfalse8/taski_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80